### PR TITLE
Feature/add snippets

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**

### CODE REVIEW

**Comment by Shane-XB-Qian** [comment]
the snip should be placed at server side? or just for vsc?
if for vsc only, then perhaps there are some local snip plugin/extension can do that already.

**Comment by EmilySeville7cfg** [comment]
> the snip should be placed at server side? or just for vsc?

It's better to place them at server side like in Bash IDE, but I don't know how to do it now, not TypeScript developer.

**Comment by Shane-XB-Qian** [comment]
yes, i think if this snip fs placed at client for vsc only, then looks unnecessary, or conflict.
// i recall vsc had general way to add snips.

if you like to add snip within lsp server package, i thought better be in server folder.

**Comment by Shane-XB-Qian** [comment]
> I prefer to have one good extension which provides these features.

i do not use vsc much, but to vim, there several plugins can generally offer snips for many langs, and can do without lsp.

but you're ok to add snips into lsp server package, (which should be in server folder), 
that would be workable for all clients (not only vsc or vim), that's a good impl as well.

**Comment by Beaglefoot** [comment]
The snippets ended up on server side. Hopefully this makes more sense and lets all editors to benefit from them.

**Comment by Shane-XB-Qian** [comment]
> but I don't know how to do it now, not TypeScript developer.

@Beaglefoot would you mind help @EmilySeville7cfg move this snip file to right place?

**Comment by Beaglefoot** [comment]
> > but I don't know how to do it now, not TypeScript developer.
> 
> @Beaglefoot would you mind help @EmilySeville7cfg move this snip file to right place?

It's already there. The last published version provides snippets on server side.

**Comment by Shane-XB-Qian** [comment]
thx, i just verified a bit, but seems not work still.
maybe should directly registered snippets.json to src/snippets.ts as const var?

**Comment by Beaglefoot** [comment]
Hate to say it but works on my side:
output

Would you mind to open an issue describing all the steps to replicate?

**Comment by Shane-XB-Qian** [comment]
// i opened #44 

seems a bit complex to me to desc the steps, i am not using vsc.
but i am trying to debug a bit, please check #44

**Pull request merged**
