### PR TITLE
Add nvim-lspconfig configuration example

### PR DESCRIPTION
**Pull request by lilibyte**
Will update again if the awk-language-server PR is merged into nvim-lspconfig

### CODE REVIEW

**Comment by Beaglefoot** [comment]
Many thanks!

I really wished someone would join in and show how such configuration is done.

**Comment by Beaglefoot** [comment]
@lilibyte You might also check 3e854556f9eaef5b69abed055bf0f1157973cd1e. Although I'm not familiar with neovim and lua, so have no idea how viable this solution is in the long run.

**Comment by Beaglefoot** [comment]
@lilibyte Could you please check that what's returned is surrounded by double curly braces (it's list of dictionaries).

I can successfully navigate between different documents in workspace with [config example from readme](https://github.com/Beaglefoot/awk-language-server#nvim-lspconfig), so I suspect a typo or something.

Could you please also check with `diff` or `vimdiff` that there no discrepancies?
```sh
diff from_readme_init.vim init.vim
```

**Comment by lilibyte** [comment]
@Beaglefoot You're right, sorry. I didn't realize I was getting two different errors. The one about `workspaceFolders.flatMap` I pasted was due to missing a set of curly braces. The reason I thought that wasn't it is because I still have an error after this: `Error: EACCES: permission denied, scandir`.

The permission discrepancy is on my end (it's just a random pikaur file in `.cache`). Since this is happening in the process of a `getAwkFilesInDir` call, does this suggest that awk-language-server is descending into the entire file tree from the cwd? Would limiting its scanning be something within the neovim config side or on the awk-lsp side?

**Comment by Beaglefoot** [comment]
Good finding! This is definitely something LS should be able to handle.

**Comment by Beaglefoot** [comment]
@lilibyte The issue with permissions is resolved in #24 and will be included in the next release.

If you'd like to check right now with master branch, I can provide some instructions on how to do so.

**Comment by lilibyte** [comment]
@Beaglefoot Thank you, I'll test it. Also, is it possible to optionally prevent LS crawling in the first place to better support the spirit of options like `single_file_support`?

**Comment by Beaglefoot** [comment]
@lilibyte I can add an option for CLI mode to skip indexing entirely. In this case only currently opened file will be analyzed. So if you `@include` some other awk-file, you won't be able to utilize renaming or navigating to symbols across files. Would this suffice?

**Comment by lilibyte** [comment]
@Beaglefoot Sounds perfect to me

**Comment by Beaglefoot** [comment]
@lilibyte Now you can start it as `awk-language-server --noIndex` which prevents crawling.

**Pull request merged**
